# C1: Wprowadzenie do PyTorch

## Podstawy pracy z tensorami

In [2]:
import torch #importowanie pakietu torch

### 1. Tworzenie tensorów w Torch

In [3]:
#pusty tensor 1D (skalar)
x = torch.empty(1)
print(x)

tensor([0.])


In [5]:
#pusty tensor 2D (macierz)
x = torch.empty(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [6]:
#tensory wielowymiarowe
x = torch.empty(2,2,2)
print(x)

tensor([[[7.1575e+21, 1.9674e-42],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])


In [13]:
#tensor liczb losowych
x = torch.rand(3,3)
print(x)

tensor([[0.7982, 0.4397, 0.6289],
        [0.9519, 0.7136, 0.8103],
        [0.4103, 0.8274, 0.3901]])


In [14]:
#tensor zer/jedynek
x = torch.zeros(2,2)
print(x)
x = torch.ones(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [15]:
#sprawdzenie typu
print(x.dtype)

#sprawdzenie rozmiaru
print(x.size())

torch.float32
torch.Size([2, 2])


In [21]:
#zmiana typu
x=torch.ones(2,2, dtype=torch.int) #inne typy: double, float, float16 itp.
print(x.dtype)

torch.int32


In [23]:
#utowrzenie tensora z list
x = torch.tensor([[1, 2, 3],
                  [2, 3, 4]])
print(x)

tensor([[1, 2, 3],
        [2, 3, 4]])


### 2. Operacje na tensorach

In [24]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x); print(y)

tensor([[0.1474, 0.2570],
        [0.2508, 0.6959]])
tensor([[0.0008, 0.7627],
        [0.6736, 0.7960]])


In [30]:
#dodawanie
z=x+y
print(z)

#lub
z = torch.add(x,y)
print(z)

#lub
y.add_(x)
print(y)

tensor([[0.2956, 1.2767],
        [1.1753, 2.1878]])
tensor([[0.2956, 1.2767],
        [1.1753, 2.1878]])
tensor([[0.2956, 1.2767],
        [1.1753, 2.1878]])


In [31]:
#odejmowanie
z=x-y
print(z)

#lub
z = torch.sub(x,y)
print(z)

#lub
y.sub_(x)
print(y)

tensor([[-0.1482, -1.0197],
        [-0.9244, -1.4919]])
tensor([[-0.1482, -1.0197],
        [-0.9244, -1.4919]])
tensor([[0.1482, 1.0197],
        [0.9244, 1.4919]])


In [32]:
#mnożenie
z=x*y
print(z)

#lub
z = torch.mul(x,y)
print(z)

#lub
y.mul_(x)
print(y)

tensor([[0.0218, 0.2621],
        [0.2319, 1.0382]])
tensor([[0.0218, 0.2621],
        [0.2319, 1.0382]])
tensor([[0.0218, 0.2621],
        [0.2319, 1.0382]])


In [33]:
#dzielenie
z=x/y
print(z)

#lub
z = torch.div(x,y)
print(z)

#lub
y.div_(x)
print(y)

tensor([[6.7470, 0.9807],
        [1.0818, 0.6703]])
tensor([[6.7470, 0.9807],
        [1.0818, 0.6703]])
tensor([[0.1482, 1.0197],
        [0.9244, 1.4919]])


In [46]:
#przeglądanie wybranych elementów tensorów
x = torch.rand(4,5)
print(x)

print(x[:, 0]) #tylko 1-sza kolumna
print(x[:, 3]) #tylko 2-ga kolumna
print(x[1, :]) #drugi wiersz
print(x[1, 2]) #pojedyńczy element
print(x[1, 2].item()) #j. w.
print(x[0:2 :]) #dwa pierwsze wiersze itd.

tensor([[6.2144e-01, 7.0903e-01, 4.5268e-01, 6.0890e-01, 7.5206e-01],
        [3.1191e-01, 6.6295e-01, 5.1434e-01, 1.2021e-01, 9.4694e-01],
        [7.5627e-01, 7.7373e-01, 1.7201e-01, 4.4788e-01, 7.5924e-01],
        [5.2884e-01, 9.0927e-04, 7.2166e-01, 5.1189e-01, 4.7568e-01]])
tensor([0.6214, 0.3119, 0.7563, 0.5288])
tensor([0.6089, 0.1202, 0.4479, 0.5119])
tensor([0.3119, 0.6629, 0.5143, 0.1202, 0.9469])
tensor(0.5143)
0.5143415927886963
tensor([[0.6214, 0.7090, 0.4527, 0.6089, 0.7521],
        [0.3119, 0.6629, 0.5143, 0.1202, 0.9469]])


In [53]:
#zmiana rozmiaru
print(x); print(x.size())

y = x.view(20) #wszystkie elementy x jako jeden wektor
print(y); print(y.size())

y = x.view(-1, 10) #2x10
print(y); print(y.size())

y = x.view(10, -1) #10x2 
print(y); print(y.size())

tensor([[6.2144e-01, 7.0903e-01, 4.5268e-01, 6.0890e-01, 7.5206e-01],
        [3.1191e-01, 6.6295e-01, 5.1434e-01, 1.2021e-01, 9.4694e-01],
        [7.5627e-01, 7.7373e-01, 1.7201e-01, 4.4788e-01, 7.5924e-01],
        [5.2884e-01, 9.0927e-04, 7.2166e-01, 5.1189e-01, 4.7568e-01]])
torch.Size([4, 5])
tensor([6.2144e-01, 7.0903e-01, 4.5268e-01, 6.0890e-01, 7.5206e-01, 3.1191e-01,
        6.6295e-01, 5.1434e-01, 1.2021e-01, 9.4694e-01, 7.5627e-01, 7.7373e-01,
        1.7201e-01, 4.4788e-01, 7.5924e-01, 5.2884e-01, 9.0927e-04, 7.2166e-01,
        5.1189e-01, 4.7568e-01])
torch.Size([20])
tensor([[6.2144e-01, 7.0903e-01, 4.5268e-01, 6.0890e-01, 7.5206e-01, 3.1191e-01,
         6.6295e-01, 5.1434e-01, 1.2021e-01, 9.4694e-01],
        [7.5627e-01, 7.7373e-01, 1.7201e-01, 4.4788e-01, 7.5924e-01, 5.2884e-01,
         9.0927e-04, 7.2166e-01, 5.1189e-01, 4.7568e-01]])
torch.Size([2, 10])
tensor([[6.2144e-01, 7.0903e-01],
        [4.5268e-01, 6.0890e-01],
        [7.5206e-01, 3.1191e-01],
        [

### 3. Konwersja pomiędzy torch a numpy

In [54]:
import numpy as np

In [64]:
#torch -> numpy
x = torch.ones(4)
print(type(x))
print(x.dtype)
print(x)
y=x.numpy()
print(type(y))
print(y.dtype)
print(y)

#Uwaga - oba obiekty wskazują do tej samej lokacji w pamięci! (jeśli implementacja na CPU)
x += 1
print(x); print(y)

<class 'torch.Tensor'>
torch.float32
tensor([1., 1., 1., 1.])
<class 'numpy.ndarray'>
float32
[1. 1. 1. 1.]
tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


In [76]:
#numpy -> torch
x = np.ones(4)
print(type(x))
print(x.dtype)
print(x)
y=torch.from_numpy(x)
print(type(y))
print(y.dtype)
print(y)

<class 'numpy.ndarray'>
float64
[1. 1. 1. 1.]
<class 'torch.Tensor'>
torch.float64
tensor([1., 1., 1., 1.], dtype=torch.float64)


### 4. Użycie GPU

In [75]:
if torch.cuda.is_available():
    dev = torch.device("cuda")
    x = torch.ones(4, device=dev) #implementacja na GPU
    
    #utworzenie tensora na CPU i przesunięcie na GPU
    y = torch.ones(4)
    t = t.to(dev)
    
    z = x+y    #operacja wykonywana z użyciem GPU
    z = z.to("cpu") #powrót na CPU
    print(z)