# Gradienty

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html




In [2]:
import torch

In [19]:
a=torch.tensor([1.0],requires_grad=True)
x=torch.tensor([-2.],requires_grad=True)

In [20]:
Q=a**2+x**3
print(Q)

tensor([-7.], grad_fn=<AddBackward0>)


In [21]:
Q.backward()

In [24]:
print("Dq/Da=",a.grad)
print("Dq/Dx=",x.grad)

Dq/Da= tensor([2.])
Dq/Dx= tensor([12.])


### This will fail

In [26]:
a=torch.tensor([1.0,2.0],requires_grad=True)
x=torch.tensor([-2.,-3.0],requires_grad=True)
Q=a**2+x**3
print(Q)
Q.backward()
print("Dq/Da=",a.grad)
print("Dq/Dx=",x.grad)

tensor([ -7., -23.], grad_fn=<AddBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

## This will work

In [27]:
a=torch.tensor([1.0,2.0],requires_grad=True)
x=torch.tensor([-2.,-3.0],requires_grad=True)
Q=a**2+x**3
print(Q)
Q.backward(gradient=torch.tensor([1.0,1.0]))
print("Dq/Da=",a.grad)
print("Dq/Dx=",x.grad)

tensor([ -7., -23.], grad_fn=<AddBackward0>)
Dq/Da= tensor([2., 4.])
Dq/Dx= tensor([12., 27.])
