In [28]:
import torch
import torch.nn as nn
class fcnn(nn.Module):
    def __init__(self,n_input=2,n_hidden=2,n_output=1):
        super(fcnn,self).__init__()
        activation=nn.Sigmoid
        
        self.input_layer=nn.Sequential(*[nn.Linear(n_input,n_hidden),activation()])
        self.output_layer=nn.Linear(n_hidden,n_output)
    def forward(self,x):
        x=self.input_layer(x)
        x=self.output_layer(x)
        return x
        

In [29]:
x=torch.tensor([[0,0],[0,1],[1,0],[1,1]],requires_grad=False,dtype=torch.float32)
y=torch.tensor([0,1,1,0],requires_grad=False,dtype=torch.float32).view(-1,1)
model=fcnn()
loss_function=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.1)

In [30]:
n_iter=6000
for epoch in range(n_iter):
    optimizer.zero_grad()
    y_predictive=model(x)
    loss=loss_function(y_predictive,y)
    loss.backward()
    optimizer.step()

In [31]:
print(y_predictive)

tensor([[8.3447e-06],
        [9.9999e-01],
        [9.9999e-01],
        [3.3379e-06]], grad_fn=<AddmmBackward0>)


In [32]:
print(loss)

tensor(3.8662e-11, grad_fn=<MseLossBackward0>)


In [13]:
y=torch.tensor([0,1,1,0],requires_grad=False,dtype=torch.float32).view(-1,1)

In [14]:
print(y)

tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [15]:
y.shape

torch.Size([4, 1])

In [17]:
x

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [2]:
nn.Module?